ORG 0000H

MOV P1, 0FFH		;SET ALL THE PINS OF PORT 1 TO HIGH

LOOP:
	CLR P2.0		;MAKE THE PORT P2: 01111111
	SETB P2.1		;
	SETB P2.2
	SETB P2.3
	SETB P2.4
	SETB P2.5
	SETB P2.6
	SETB P2.7

	JNB P2.0, LOOP	;CHECK IF PIN 0 OF PORT 2 IS HIGH. IF NOT, LOOP AGAIN
	
	NOP
	NOP
	NOP	;FEW NOPS JUST TO GIVE SOME TIME
	NOP
	NOP
	NOP
	
	MOV ACC, #00H	;CLEAR ACCUMULATOR WHERE WE WILL KEEP THE VALUE OF DATA COMING INTO P2.1, P2.2, P2.3
	JB P2.1, CHECK_P2.2	;CHECK IF P2.1 IS ACTIVE. IF ACTIVE CONTINUE TO NEXT LINE, OTHERWISE SKIP AND PROCEED TO CHECK P2.2
	ADD A,#1		;ADD WEIGHT OF PIN 1 WHICH IS 1 IN DECIMAL
CHECK_P2.2:
	JB P2.2, CHECK_P2.3	;CHECK IF P2.2 IS ACTIVE. IF ACTIVE CONTINUE TO NEXT LINE, OTHERWISE SKIP AND PROCEED TO CHECK P2.3
	ADD A, #2
CHECK_P2.3:
	JB P2.3, NEXT	;CHECK IF P2.1 IS ACTIVE. IF ACTIVE CONTINUE TO NEXT LINE, OTHERWISE FINISH AND PROCEED TO NEXT OPERATION
	ADD A, #4

NEXT:
	CJNE A, #1, CHECK2		;COMPARE AND JUMP TO CHECK2 IF ACC IS NOT EQUAL TO VALUE 1. OTHERWISE PROCEED TO CHECK IF P2.4(TOGGLE) IS SET OR NOT
	JNB P2.4, SET1			;IF P2.4 IS ZERO PROCEED TO TURN ON FIRST DEVICE
	JB P2.4, CLR1			;IF P2.4 IS HIGH, PROCEED TO TURN OFF FIRST DEVICE 
	
SET1:
	CLR P1.1
	SJMP LOOP				;RETURN TO START
CLR1:
	SETB P1.1		
	SJMP LOOP				;RETURN TO START
	

CHECK2:
	CJNE A, #2, CHECK3		;COMPARE AND JUMP TO CHECK3 IF ACC IS NOT EQUAL TO VALUE 2. OTHERWISE PROCEED TO CHECK IF P2.4(TOGGLE) IS SET OR NOT
	JNB P2.4, SET2			;IF P2.4 IS ZERO PROCEED TO TURN ON FIRST DEVICE
	JB P2.4, CLR2			;IF P2.4 IS HIGH, PROCEED TO TURN OFF FIRST DEVICE 
	
SET2:
	CLR P1.2
	SJMP LOOP				;RETURN TO START
CLR2:
	SETB P1.2		
	SJMP LOOP				;RETURN TO START
	
	
CHECK3:
	CJNE A, #3, CHECK4		;COMPARE AND JUMP TO CHECK4 IF ACC IS NOT EQUAL TO VALUE 3. OTHERWISE PROCEED TO CHECK IF P2.4(TOGGLE) IS SET OR NOT
	JNB P2.4, SET3			;IF P2.4 IS ZERO PROCEED TO TURN ON FIRST DEVICE
	JB P2.4, CLR3			;IF P2.4 IS HIGH, PROCEED TO TURN OFF FIRST DEVICE 
	
SET3:
	CLR P1.3
	SJMP LOOP				;RETURN TO START
CLR3:
	SETB P1.3		
	SJMP LOOP				;RETURN TO START
	
	
CHECK4:
	CJNE A, #4, CHECK5		;COMPARE AND JUMP TO CHECK5 IF ACC IS NOT EQUAL TO VALUE 4. OTHERWISE PROCEED TO CHECK IF P2.4(TOGGLE) IS SET OR NOT
	JNB P2.4, SET4			;IF P2.4 IS ZERO PROCEED TO TURN ON FIRST DEVICE
	JB P2.4, CLR4			;IF P2.4 IS HIGH, PROCEED TO TURN OFF FIRST DEVICE 
	
SET4:
	CLR P1.4
	LJMP LOOP				;RETURN TO START
CLR4:
	SETB P1.4		
	LJMP LOOP				;RETURN TO START
	
	
CHECK5:
	CJNE A, #5, CHECK6		;COMPARE AND JUMP TO CHECK2 IF ACC IS NOT EQUAL TO VALUE 1. OTHERWISE PROCEED TO CHECK IF P2.4(TOGGLE) IS SET OR NOT
	JNB P2.4, SET5			;IF P2.4 IS ZERO PROCEED TO TURN ON FIRST DEVICE
	JB P2.4, CLR5			;IF P2.4 IS HIGH, PROCEED TO TURN OFF FIRST DEVICE 
	
SET5:
	CLR P1.5
	LJMP LOOP				;RETURN TO START
CLR5:
	SETB P1.5		
	LJMP LOOP				;RETURN TO START
	
	
CHECK6:
	CJNE A, #6, CHECK7		;COMPARE AND JUMP TO CHECK2 IF ACC IS NOT EQUAL TO VALUE 1. OTHERWISE PROCEED TO CHECK IF P2.4(TOGGLE) IS SET OR NOT
	JNB P2.4, SET6			;IF P2.4 IS ZERO PROCEED TO TURN ON FIRST DEVICE
	JB P2.4, CLR6			;IF P2.4 IS HIGH, PROCEED TO TURN OFF FIRST DEVICE 
	
SET6:
	CLR P1.6
	LJMP LOOP				;RETURN TO START
CLR6:
	SETB P1.6		
	LJMP LOOP				;RETURN TO START
	
	
CHECK7:
	CJNE A, #7, FINISH		;COMPARE AND JUMP TO FINISH IF ACC IS NOT EQUAL TO VALUE 7. OTHERWISE PROCEED TO CHECK IF P2.4(TOGGLE) IS SET OR NOT
	JNB P2.7, SET7			;IF P2.4 IS ZERO PROCEED TO TURN ON FIRST DEVICE
	JB P2.7, CLR7			;IF P2.4 IS HIGH, PROCEED TO TURN OFF FIRST DEVICE 
	
SET7:
	CLR P1.7
	LJMP LOOP				;RETURN TO START
CLR7:
	SETB P1.7		
	LJMP LOOP				;RETURN TO START
	
FINISH:
	LJMP LOOP
	
	
END
